from django.test import TestCase
from django.urls import reverse
from .models import Video

# As the API continues to grow we would want to write tests here
# They would look something like the following:

# Example of testing a Model
class VideoTest(TestCase):
    def test_constructor(self):
        entry = Video(file_name="Example")
        self.assertEqual(entry.file_name, "Example")

# Example of testing a View
class GetVideosTest(TestCase):
    def test_get_videos(self):
        # Name of /videos URL generated by the register function
        url = reverse('video-list')
        response = self.client.get(url)
        self.assertEqual(response.status_code, 200)
